version: '3.9'

services:
  math-service: # gRPC сервер
    container_name: math-service
    build:
      context: ./MathService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"  
    environment:
      - ASPNETCORE_Kestrel__Endpoints__Grpc__Protocols=Http2
      - ASPNETCORE_ENVIRONMENT=Development

  calculator-service: # Web API клиент
    container_name: calculator-service
    build:
      context: ./CalculatorService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"  
    depends_on:
      - math-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
