version: '3.8'

services:
  calculator: # gRPC сервер
    container_name: calculator-service
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:8080"  
    environment:
      - ASPNETCORE_Kestrel__Endpoints__Grpc__Protocols=Http2

  calculatorclient: # Web API клиент
    container_name: calculator-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5002:8080"  
    depends_on:
      - calculator
